name: CornCob builder workflow

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Rust (stable) toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build in release mode, if its a release
        uses: actions-rs/cargo@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          command: build
          args: --locked --all --release

      - name: Build in debug mode
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --locked --all

      - name: 'Install (Cargo) binutils, if its release.'
        if: startsWith(github.ref, 'refs/tags/')
        run:
          cargo install cargo-binutils && rustup component add llvm-tools-preview

      - name: Strip the executables, if its a release
        if: startsWith(github.ref, 'refs/tags/')
        run: cargo strip --release -- --strip-all

      - name: Create release, and upload artifact
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            target/release/corncob
            target/release/corncobc
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

      - name: Upload debug build artifact
        uses: actions/upload-artifact@v2
        with:
          name: CornCob-debug
          path: |
            target/debug/corncob
            target/debug/corncobc
