name: CornCob builder workflow

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Rust (stable) toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build in debug mode
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --locked --all

      - name: Upload debug build artifact
        uses: actions/upload-artifact@v3
        with:
          name: CornCob-debug
          path: |
            target/debug/corncob
            target/debug/corncobc
